#!/usr/bin/env bash

# Allow expanding aliases after sudo
alias sudo="sudo "

##
## Navigation
##

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias docs="cd ~/Documents"
[ -r ~/repos ] && alias repos="cd ~/repos"

##
## Misc
##

# Confirm before overwriting
alias cp='cp -i'

# Improve readability of commands
alias df='df -h'  # Human-readable sizes
alias free='free -m'  # Show sizes in MB

alias np='nano -w PKGBUILD'
alias reload='exec $SHELL -l'
