#!/usr/bin/env bash

##
## ex - archive extractor
## usage: ex <file>
##

ex()
{
    if [[ -f $1 ]] ; then
        case $1 in
            *.tar.bz2)   tar xjf "$1"    ;;
            *.tar.gz)    tar xzf "$1"    ;;
            *.bz2)       bunzip2 "$1"    ;;
            *.rar)       unrar x "$1"    ;;
            *.gz)        gunzip "$1"     ;;
            *.tar)       tar xf "$1"     ;;
            *.tbz2)      tar xjf "$1"    ;;
            *.tgz)       tar xzf "$1"    ;;
            *.zip)       unzip "$1"      ;;
            *.Z)         uncompress "$1" ;;
            *.7z)        7z x "$1"       ;;
            *)           echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

##
## fm
## usage: fm <optional-dir>
##
## Opens file manager in a subshell. Defaults to the current working directory.
##

fm() {
    if [[ -z $1 ]] ; then
        (xdg-open .) > /dev/null 2>&1
    elif [[ -d $1 ]] ; then
        (xdg-open "$1") > /dev/null 2>&1
    else
        echo "'$1' is not a valid directory"
    fi
}

##
## mcd - mkdir and cd
## usage: mcd <path/to/new/dir>
##
## If multiple paths are supplied, it creates as many directories and navigates into the
## first one.
##

mcd() {
    mkdir -p "$@" && cd "$1" || return
}

##
## tmpd - create temporary directory and cd
## usage: tmpd <optional_label>
##

tmpd() {
    local temp_dir
    if [[ $# -eq 0 ]]; then
        temp_dir=$(mktemp -d)
    else
        temp_dir=$(mktemp -d -t "${1}.XXXXXXXXXX")
    fi
    cd "$temp_dir" || return
}
