#!/usr/bin/env bash

##
## NVM
##

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load NVM
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Load NVM bash completion

##
## Poetry
##

export PATH="$HOME/.poetry/bin:$PATH"
# To enable completions, see `poetry help completions`.

##
## Pyenv
##

[ -x "$(command -v pyenv)" ] && eval "$(pyenv init -)"
