#!/usr/bin/env bash

##
## Customize `less`: source highlighting, lesspipe
##

export LESSPIPE_PATH="/usr/share/source-highlight/src-hilite-lesspipe.sh"
if [[ -f $LESSPIPE_PATH ]]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
fi

##
## NVM
##

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"  # Load NVM
[[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"  # Load NVM bash completion

##
## Python
##

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[[ -x $(command -v pyenv) ]] && eval "$(pyenv init -)"

# Enable pip autocompletion
eval "$(pip completion --zsh)"

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"
# To enable completions, see `poetry help completions`.

##
## Ruby
##

if [[ -x $(command -v ruby) ]]; then
    GEM_USER_DIR=$(ruby -r rubygems -e 'puts Gem.user_dir')
    export PATH="$GEM_USER_DIR/bin:$PATH"
fi

##
## The Fuck
## Command aliases: fk, fuck
##

if [[ -x $(command -v thefuck) ]]; then
    eval "$(thefuck --alias)"
    alias fk=fuck
fi
