##
## PATH expansions
##

# User binaries
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[[ -x $(command -v pyenv) ]] && eval "$(pyenv init -)"

# Ruby
if [[ -x $(command -v ruby) ]]; then
    export GEM_USER_DIR=$(ruby -r rubygems -e 'puts Gem.user_dir')
    export PATH="$GEM_USER_DIR/bin:$PATH"
fi

# Rust
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

##
## Defaults
##

export EDITOR=/usr/bin/vim  # Set vim as default editor
export DELTA_PAGER='less -rX'  # Render hyperlinks correctly

##
## Colorize output
##

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

# Customize `less`: source highlighting, lesspipe
export LESSPIPE_PATH="/usr/share/source-highlight/src-hilite-lesspipe.sh"
if [[ -f $LESSPIPE_PATH ]]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
fi

##
## WSL compatibility settings
##

if grep -qi microsoft /proc/version; then
    export WSL=true
    unsetopt BG_NICE  # https://github.com/Microsoft/BashOnWindows/issues/1887
else
    export WSL=false
fi
