##
## Misc options
##

setopt autocd  # Automatically cd to a directory path if it's not a valid command
setopt extendedglob  # Extended globbing
setopt nobeep
setopt numericglobsort  # Sort files numerically when it makes sense
# setopt nocaseglob  # Make globbing case-insensitive
setopt rcexpandparam  # Array expansion with parameters

##
## History
##

HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=500

setopt appendhistory  # Immediately append history instead of overwriting
setopt histignorealldups  # If a new command is a duplicate, remove the older one

##
## Shell-related exports
##

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

##
## Autoload
##

# Autocompletion
autoload -Uz compinit
compinit -d

# Colors
autoload -Uz colors
colors
eval $(dircolors -b ~/.dir_colors)

##
## Plugins (loaded with zplug)
##

source ~/.zplug/init.zsh

# Use syntax highlighting
zplug "zsh-users/zsh-syntax-highlighting"

# History substring search
zplug "zsh-users/zsh-history-substring-search"
# Bind UP and DOWN arrow keys to history substring search.
# (Base keybindings are configured in ~/.zbindkeys)
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Enable Fish-like autosuggestions
zplug "zsh-users/zsh-autosuggestions"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

# Autojump
if [[ -x $(command -v autojump) ]]; then
    source /usr/share/autojump/autojump.sh
    zplug "wting/autojump"
fi

if zplug check || zplug install; then
    zplug load
fi

##
## Complementary files
##

## Shared resources needed for other complementary files
source ~/.shell.d/shared

# Required zsh complementary files
source ~/.shell.d/zbindkeys  # Keybindings
source ~/.shell.d/zprompt  # Prompt

# Optional bash complementary files
for file in ~/.shell.d/{aliases,extras,functions,misc}; do
    [[ -r $file ]] && [[ -f $file ]] && source "$file";
done
unset file
