##
## Misc options
##

setopt autocd  # Automatically cd to a directory path if it's not a valid command
setopt extendedglob  # Extended globbing
setopt nobeep
setopt numericglobsort  # Sort files numerically when it makes sense
# setopt nocaseglob  # Make globbing case-insensitive
setopt rcexpandparam  # Array expansion with parameters

##
## History
##

HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=500

setopt appendhistory  # Immediately append history instead of overwriting
setopt histignorealldups  # If a new command is a duplicate, remove the older one

##
## Shell-related exports
##

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

##
## Autoload
##

# Autocompletion
autoload -Uz compinit
compinit -d

# Colors
autoload -Uz colors
colors

##
## Plugins
##

# Use syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
# Bind UP and DOWN arrow keys to history substring search.
# (Base keybindings are configured in ~/.zbindkeys)
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

##
## Complementary files
##

# Required zsh complementary files
source ~/.zbindkeys  # Keybindings
source ~/.zprompt  # Prompt

# Optional bash complementary files
for file in ~/.{aliases,extras,functions,misc}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done
unset file
