#!/bin/bash

protected_branches=(main master)
remote_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ ${protected_branches[*]} =~ $remote_branch ]]; then
    read -p "Push to $remote_branch? [Y|n] " -r answer < /dev/tty
    answer=${answer:-y}
    if echo "$answer" | grep -E '^[Yy]$' > /dev/null; then
        exit 0  # allow push
    fi
    exit 1  # stop push
else
    exit 0  # allow push
fi
