#!/usr/bin/env bash

##
## Customize `less`: source highlighting, lesspipe
##

export LESSPIPE_PATH="/usr/share/source-highlight/src-hilite-lesspipe.sh"
if [[ -f $LESSPIPE_PATH ]]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
fi

##
## NVM (lazy load)
##

export NVM_DIR="$HOME/.nvm"

_load_nvm() {
    [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"  # Load NVM
    [[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"  # Load NVM bash completion
}

# shellcheck disable=SC2207
node_binaries=($(echo "$NVM_DIR"/v0*/bin/*(N) "$NVM_DIR"/versions/*/*/bin/*(N) |
        xargs --no-run-if-empty --max-args=1 basename |
        sort |
        uniq
    ))
[[ -x $(command -v yarn) ]] && node_binaries+=('yarn')
node_binaries+=('nvm')

_lazy_load _load_nvm "${node_binaries[@]}"

##
## Python
##

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[[ -x $(command -v pyenv) ]] && eval "$(pyenv init -)"

# Enable pip autocompletion
[[ -x $(command -v pip) ]] && eval "$(pip completion --zsh)"

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"
# To enable completions, see `poetry help completions`.

##
## Ruby
##

if [[ -x $(command -v ruby) ]]; then
    GEM_USER_DIR=$(ruby -r rubygems -e 'puts Gem.user_dir')
    export PATH="$GEM_USER_DIR/bin:$PATH"
fi

##
## Others
##

# Autojump
# shellcheck disable=SC1091
[[ -x $(command -v autojump) ]] && source /usr/share/autojump/autojump.sh

# The Fuck
if [[ -x $(command -v thefuck) ]]; then
    eval "$(thefuck --alias)"
    alias fk=fuck
fi
