name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Shellcheck
        run: bash ./scripts/shellcheck.sh
